application: fanflashblog
version: 1
runtime: go
api_version: go1
default_expiration: "7d"

handlers:
- url: /css
  static_dir: gorbled/static/css

- url: /js
  static_dir: gorbled/static/js

- url: /img
  static_dir: gorbled/static/img

- url: /favicon.ico
  static_files: gorbled/static/favicon.ico
  upload: gorbled/static/favicon.ico

- url: /.*
  script: _go_app
