application: fanflashblog
version: 1
runtime: go
api_version: go1
default_expiration: "7d"

handlers:
- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /img
  static_dir: static/img

- url: /bdsitemap.txt
  static_files: static/bdsitemap.txt

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /.*
  script: _go_app
